### ISSUE TITLE
Errors in script for production submission 

### ISSUE THREAD

**Issue by DOH-KEW4303** [CDCgov/seqsender#2]
Hello, I am trying to do our first production submission and this is the output I am getting.

Traceback (most recent call last):
  File "seqsender.py", line 616, in <module>
    main()
  File "seqsender.py", line 591, in main
    submission_preparation.process_submission(args.unique_name, args.fasta, args.metadata, os.path.join(os.path.dirname(os.path.abspath(__file__)), "config_files", args.config))
  File "/root/miniconda3/seqsender/submission_preparation.py", line 493, in process_submission
    main_df = merge(fasta_file, metadata_file)
  File "/root/miniconda3/seqsender/submission_preparation.py", line 228, in merge
    main_df = fasta.merge(metadata, left_on = "fasta_name_orig",  right_on = config_dict["general"]["fasta_sample_name_col"], how = "left")
  File "/root/miniconda3/envs/seqsender/lib/python3.6/site-packages/pandas/core/frame.py", line 7963, in merge
    validate=validate,
  File "/root/miniconda3/envs/seqsender/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 87, in merge
    validate=validate,
  File "/root/miniconda3/envs/seqsender/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 652, in __init__
    ) = self._get_merge_keys()
  File "/root/miniconda3/envs/seqsender/lib/python3.6/site-packages/pandas/core/reshape/merge.py", line 1005, in _get_merge_keys
    right_keys.append(right._get_label_or_level_values(rk))
  File "/root/miniconda3/envs/seqsender/lib/python3.6/site-packages/pandas/core/generic.py", line 1563, in _get_label_or_level_values
    raise KeyError(key)
KeyError: 'specimen_collector_sample_id'

**Comment by leebrian** [comment]
@dthoward96  said this is completed and solved and assigning to help with documenting and closing out.

**Comment by dthoward96** [comment]
This is related to metadata issues. specimen_collector_sample_id is the metadata column the script was looking for and was unable to find it. Updating the field for "fasta_sample_name_col" in the config file to the correct metadata header should resolve this.
